- name: Determine if PGRestAPI already cloned
  stat: path={{pgrestapi_install_path}}/PGRestAPI/.git
  register: repo

- name: Clone PGRestAPI if not found
  shell: (cd {{pgrestapi_install_path}} && git clone https://github.com/spatialdev/PGRestAPI.git)
  when: repo.stat.exists == False

- name: Get latest PGRestAPI repo master branch
  shell: (cd {{pgrestapi_install_path}}/PGRestAPI && git pull origin master)
  when: repo.stat.exists == True

- name: Install PGRestAPI
  shell: (cd {{pgrestapi_install_path}}/PGRestAPI && npm install)

- name: Confgure settings.js file
  template: src={{pgrestapi_settings_template_path}} dest={{pgrestapi_install_path}}/PGRestAPI/settings/settings.js force=yes
