- name: git checkout PGRestAPI repository
  git:
    accept_hostkey: yes
    repo: "git@github.com:spatialdev/PGRestAPI.git"
    dest: "{{ pgrestapi_install_path }}/PGRestAPI"
    version: "{{ pgrestapi_version }}"


- name: Install PGRestAPI
  shell: (cd {{pgrestapi_install_path}}/PGRestAPI && npm install)

- name: Confgure settings.js file
  template: src={{pgrestapi_settings_template_path}} dest={{pgrestapi_install_path}}/PGRestAPI/settings/settings.js force=yes
